"""empty message

Revision ID: 514f3ba65d39
Revises: 8250d5ec7b49
Create Date: 2021-09-08 00:41:20.467356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514f3ba65d39'
down_revision = '8250d5ec7b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog', sa.Column('cover_image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dog', 'cover_image')
    # ### end Alembic commands ###
