"""empty message

Revision ID: 647b55d3fc8a
Revises: 514f3ba65d39
Create Date: 2021-09-08 14:55:53.804612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647b55d3fc8a'
down_revision = '514f3ba65d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dog', sa.Column('location', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dog', 'location')
    # ### end Alembic commands ###
